import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { Footer, Header } from "@/components/SiteChrome";
import { services, slugs, type Lang, type ServiceSlug } from "@/lib/madapath";
export function generateStaticParams() { return ["fr", "en"].flatMap(lang => slugs.map(slug => ({ lang, slug }))); }
export async function generateMetadata({ params }: { params: Promise<{ lang: string; slug: string }> }): Promise<Metadata> { const { lang, slug } = await params; if ((lang !== "fr" && lang !== "en") || !slugs.includes(slug as ServiceSlug)) return {}; const s = services[slug as ServiceSlug][lang as Lang]; return { title: s.name, description: s.short }; }
export default async function ServicePage({ params }: { params: Promise<{ lang: string; slug: string }> }) {
  const { lang: rawLang, slug: rawSlug } = await params; if ((rawLang !== "fr" && rawLang !== "en") || !slugs.includes(rawSlug as ServiceSlug)) notFound(); const lang = rawLang as Lang, slug = rawSlug as ServiceSlug, s = services[slug][lang]; const fr = lang === "fr";
  return <div className="site-shell"><Header lang={lang} /><main><section className="service-hero"><div className="container"><span className="eyebrow">{s.name}</span><h1>{s.title}</h1><p className="lead">{s.intro}</p></div></section><section className="section"><div className="container content-grid"><article className="content-copy"><h2>{fr ? "Ce que MadaPath fait pour vous" : "What MadaPath handles for you"}</h2><p>{fr ? "Nous commençons par comprendre votre situation, puis nous constituons le dossier et effectuons les procédures réalisables à votre place. Vous êtes sollicité pour fournir les pièces, signer lorsque nécessaire et vous présenter uniquement aux étapes où l’administration exige votre présence, notamment la photographie, la biométrie ou certains entretiens." : "We first assess your situation, then build the file and handle every procedure that can legally be completed on your behalf. You provide documents, sign where required and attend only the steps where authorities require your presence, including photographs, biometrics or certain interviews."}</p><ul className="checklist">{s.items.map(item => <li key={item}>{item}</li>)}</ul><h2 style={{ marginTop: 50 }}>{fr ? "Une prise en charge réelle, sans fausse promesse" : "Real handling, without false promises"}</h2><p>{fr ? "MadaPath prépare, dépose et suit les démarches dans les limites autorisées. La décision finale et les délais restent du ressort des administrations compétentes." : "MadaPath prepares, submits and follows procedures within the authorised limits. Final decisions and processing times remain with the competent authorities."}</p></article><aside className="sidebox"><h3>{fr ? "Vous n’êtes plus seul face aux démarches" : "You are no longer handling it alone"}</h3><p>{fr ? "Après le pré-diagnostic, nous déterminons ce que MadaPath peut effectuer pour vous et les rares étapes où votre présence sera obligatoire." : "After the pre-assessment, we identify what MadaPath can handle for you and the limited steps where you must attend in person."}</p><a className="button" href={`/${lang}#diagnostic`}>{fr ? "Évaluer mon dossier" : "Assess my case"}</a></aside></div></section></main><Footer lang={lang} /></div>;
}
