export type Lang = "fr" | "en";
export const slugs = ["travailleur", "famille", "retraite", "investisseur"] as const;
export type ServiceSlug = (typeof slugs)[number];
export const copy = {
  fr: {
    top: "Accompagnement administratif à Antananarivo · Français / English", nav: { services: "Services", method: "Notre méthode", cta: "Évaluer mon dossier" },
    eyebrow: "Votre installation, notre chemin commun", title: <>Vos démarches à Madagascar, enfin <em>plus claires.</em></>,
    lead: "MadaPath prend en charge vos démarches de visa, de résidence, d’emploi et d’installation à Madagascar — de la préparation du dossier aux procédures et au suivi auprès des organismes concernés.", primary: "Évaluer mon projet", secondary: "Découvrir nos services",
    trust: ["Démarches prises en charge", "Suivi personnalisé", "Présence requise seulement si nécessaire"], cardTitle: "Nous avançons à votre place", cardText: "Nous préparons, déposons et suivons les démarches réalisables par mandat. Vous intervenez uniquement lorsqu’une présence personnelle est obligatoire.", steps: ["Comprendre votre situation", "Constituer et déposer le dossier", "Suivre la procédure jusqu’à sa clôture"],
    servicesEyebrow: "Des parcours selon votre situation", servicesTitle: "Une expertise, quatre chemins", servicesIntro: "Chaque statut répond à des conditions différentes. Nous construisons l’accompagnement autour de votre réalité, pas autour d’une formule générique.", learn: "Voir le parcours →",
    methodEyebrow: "La méthode MadaPath", methodTitle: "Clair du premier échange au dernier document", methodIntro: "Notre rôle est de transformer une procédure complexe en étapes compréhensibles et maîtrisées.",
    method: [["Diagnostic", "Nous identifions votre objectif, votre statut actuel et les points de vigilance."], ["Collecte", "Nous vous demandons uniquement les pièces et informations indispensables à votre situation."], ["Prise en charge", "Nous préparons et effectuons les procédures possibles auprès de l’EDBM, des services consulaires, de TLScontact ou des administrations concernées."], ["Suivi", "Nous suivons le dossier, vous informons de son évolution et vous accompagnons lorsque votre présence est obligatoire."]],
    diagEyebrow: "Pré-diagnostic gratuit", diagTitle: "Quel est votre projet à Madagascar ?", diagText: "Choisissez votre situation pour identifier le parcours qui correspond le mieux à votre projet. Ce premier repère ne remplace pas l’étude personnalisée de votre dossier.", diagQuestion: "Votre objectif principal", diagButton: "Voir mon parcours", resultPrefix: "Votre point de départ :",
    footerText: "L’accompagnement administratif humain pour avancer sereinement à Madagascar.", footerNav: "Navigation", footerLegal: "Informations", legal: "MadaPath fournit une assistance administrative et ne garantit jamais une décision relevant des autorités compétentes.",
  },
  en: {
    top: "Administrative support in Antananarivo · Français / English", nav: { services: "Services", method: "Our method", cta: "Assess my case" },
    eyebrow: "Your move, a path we take together", title: <>Your move to Madagascar, made <em>clearer.</em></>,
    lead: "MadaPath handles your visa, residency, work and settling-in procedures — from preparing the file to submissions and follow-up with the relevant authorities.", primary: "Assess my project", secondary: "Explore our services",
    trust: ["Procedures handled for you", "Personal follow-up", "Attend only when required"], cardTitle: "We move the process forward for you", cardText: "We prepare, submit and follow every procedure that can be handled under mandate. You step in only when personal attendance is compulsory.", steps: ["Understand your situation", "Prepare and submit the file", "Follow the process through completion"],
    servicesEyebrow: "A path for every situation", servicesTitle: "One expertise, four paths", servicesIntro: "Every status comes with different conditions. We shape the support around your actual situation, not a generic package.", learn: "Explore this path →",
    methodEyebrow: "The MadaPath method", methodTitle: "Clear from the first call to the final document", methodIntro: "We turn complex procedures into understandable, manageable steps.",
    method: [["Assessment", "We identify your goal, current status and potential risks."], ["Collection", "We request only the documents and information required for your situation."], ["Handling", "We prepare and carry out eligible procedures with EDBM, consular services, TLScontact or the relevant authorities."], ["Follow-up", "We track your file, keep you informed and attend with you when your personal presence is compulsory."]],
    diagEyebrow: "Free pre-assessment", diagTitle: "What brings you to Madagascar?", diagText: "Select your situation to identify the path most relevant to your plans. This first guide does not replace a personalised case review.", diagQuestion: "Your main goal", diagButton: "See my path", resultPrefix: "Your starting point:",
    footerText: "Human administrative support for a smoother journey in Madagascar.", footerNav: "Navigation", footerLegal: "Information", legal: "MadaPath provides administrative assistance and never guarantees decisions made by the competent authorities.",
  },
};
export const services = {
  travailleur: { icon: "↗", fr: { name: "Travailler à Madagascar", short: "Autorisation d’emploi, visa transformable et parcours de résidence pour salariés expatriés.", title: "Travailler à Madagascar en toute conformité", intro: "Votre autorisation d’emploi et votre statut de résidence doivent avancer dans le bon ordre. MadaPath prend en charge les procédures réalisables et coordonne les pièces, les acteurs et les échéances.", items: ["Analyse de votre situation professionnelle", "Collecte et contrôle des pièces", "Procédure d’autorisation d’emploi auprès de l’EDBM", "Préparation et dépôt des démarches visa et résidence", "Suivi des échéances et renouvellements"] }, en: { name: "Work in Madagascar", short: "Work authorisation, transformable visa and residency path for expatriate employees.", title: "Work in Madagascar with a compliant path", intro: "Your work authorisation and residency status must move forward in the right order. MadaPath handles eligible procedures and coordinates documents, stakeholders and deadlines.", items: ["Professional situation assessment", "Document collection and verification", "EDBM work-authorisation procedure", "Visa and residency preparation and submission", "Deadline and renewal follow-up"] } },
  famille: { icon: "⌂", fr: { name: "Couples et familles", short: "Regroupement familial, pièces d’état civil et installation des proches à Madagascar.", title: "Réunir votre famille à Madagascar", intro: "Les démarches familiales demandent autant de rigueur que de sensibilité. Nous constituons le dossier, effectuons les formalités possibles et anticipons les documents difficiles à obtenir.", items: ["Étude du lien familial et du statut du résident", "Collecte et vérification des actes", "Constitution et dépôt du dossier de regroupement", "Suivi auprès des organismes concernés", "Accompagnement aux rendez-vous exigeant votre présence"] }, en: { name: "Couples & families", short: "Family reunification, civil-status documents and settling relatives in Madagascar.", title: "Bring your family together in Madagascar", intro: "Family procedures require both precision and care. We build the file, handle eligible formalities and anticipate documents that may take longer to obtain.", items: ["Family link and sponsor status review", "Civil document collection and verification", "Family reunification file preparation and submission", "Follow-up with the relevant authorities", "Support at appointments requiring your presence"] } },
  retraite: { icon: "☀", fr: { name: "Retraite à Madagascar", short: "Visa résident retraité et démarches pour construire une installation durable.", title: "Préparer votre retraite à Madagascar", intro: "S’installer durablement suppose de sécuriser son statut et ses justificatifs avant le départ. Nous prenons en charge les formalités réalisables jusqu’au suivi de votre résidence.", items: ["Diagnostic du projet de résidence", "Collecte et vérification des justificatifs", "Procédure de visa transformable", "Démarches de visa long séjour et résidence", "Suivi du dossier auprès des services concernés"] }, en: { name: "Retire in Madagascar", short: "Retiree residency visa and procedures for a long-term move.", title: "Prepare your retirement in Madagascar", intro: "A long-term move means securing your status and supporting documents before departure. We handle eligible formalities through to residency follow-up.", items: ["Residency project assessment", "Supporting-document collection and verification", "Transformable visa procedure", "Long-stay visa and residency procedures", "Follow-up with the relevant authorities"] } },
  investisseur: { icon: "◇", fr: { name: "Investir et entreprendre", short: "Résidence investisseur et coordination administrative de votre projet professionnel.", title: "Investir à Madagascar avec une feuille de route claire", intro: "Votre projet d’entreprise et votre situation d’immigration sont liés. MadaPath organise et exécute les procédures administratives réalisables dans le bon ordre.", items: ["Cadrage du projet et du statut visé", "Collecte des documents société et dirigeant", "Procédures du parcours investisseur", "Dépôts et coordination avec l’EDBM et vos conseils", "Suivi administratif du dossier de résidence"] }, en: { name: "Invest & build", short: "Investor residency and administrative coordination for your business project.", title: "Invest in Madagascar with a clear roadmap", intro: "Your business project and immigration status are connected. MadaPath organises and handles eligible administrative procedures in the right order.", items: ["Project and target-status framing", "Company and director document collection", "Investor-path procedures", "Submissions and coordination with EDBM and advisers", "Administrative residency follow-up"] } },
};
