export type Lang = "fr" | "en";

export const SITE_URL = "https://madapath.com";
export const PHONE = "+261349320184";
export const PHONE_DISPLAY = "034 93 201 84";
export const EMAIL = "jonathanrazafiarijaona@gmail.com";
export const WHATSAPP_MSG_FR = encodeURIComponent("Bonjour MadaPath, je souhaite obtenir des informations concernant vos services d’accompagnement à Madagascar.");
export const WHATSAPP_MSG_EN = encodeURIComponent("Hello MadaPath, I would like more information about your assistance services in Madagascar.");
export const WHATSAPP_LINK = `https://wa.me/261349320184?text=`;
export const TEL_LINK = `tel:${PHONE}`;

export const slugs = ["travailleur", "famille", "investisseur"] as const;
export type ServiceSlug = (typeof slugs)[number];

export const copy = {
  fr: {
    lang: "fr" as const,
    top: "Accompagnement administratif à Antananarivo · Français / English",
    nav: { services: "Services", method: "Notre méthode", contact: "Contact", cta: "Évaluer mon dossier" },
    eyebrow: "Votre installation, notre chemin commun",
    title: (
      <>
        Vos démarches à Madagascar, enfin <em>plus claires.</em>
      </>
    ),
    lead: "MadaPath prend en charge vos démarches pour travailler, réunir votre famille ou investir à Madagascar — de la préparation du dossier aux procédures et au suivi auprès des organismes concernés.",
    primary: "Évaluer mon projet",
    secondary: "Découvrir nos services",
    trust: [
      "Démarches prises en charge",
      "Suivi personnalisé",
      "Présence requise seulement si nécessaire",
    ],
    cardTitle: "Nous avançons à votre place",
    cardText: "Nous préparons, déposons et suivons les démarches réalisables par mandat. Vous intervenez uniquement lorsqu’une présence personnelle est obligatoire.",
    steps: [
      "Comprendre votre situation",
      "Constituer et déposer le dossier",
      "Suivre la procédure jusqu’à sa clôture",
    ],
    servicesEyebrow: "Des parcours selon votre situation",
    servicesTitle: "Une expertise, trois chemins",
    servicesIntro: "Chaque statut répond à des conditions différentes. Nous construisons l’accompagnement autour de votre réalité, pas autour d’une formule générique.",
    learn: "Voir le parcours →",
    methodEyebrow: "La méthode MadaPath",
    methodTitle: "Clair du premier échange au dernier document",
    methodIntro: "Notre rôle est de transformer une procédure complexe en étapes compréhensibles et maîtrisées.",
    method: [
      [
        "Diagnostic",
        "Nous identifions votre objectif, votre statut actuel et les points de vigilance.",
      ],
      [
        "Collecte",
        "Nous vous demandons uniquement les pièces et informations indispensables à votre situation.",
      ],
      [
        "Prise en charge",
        "Nous préparons et effectuons les procédures possibles auprès de l’EDBM, des services consulaires, de TLScontact ou des administrations concernées.",
      ],
      [
        "Suivi",
        "Nous suivons le dossier, vous informons de son évolution et vous accompagnons lorsque votre présence est obligatoire.",
      ],
    ],
    diagEyebrow: "Pré-diagnostic gratuit",
    diagTitle: "Quel est votre projet à Madagascar ?",
    diagText: "Choisissez votre situation pour identifier le parcours qui correspond le mieux à votre projet. Ce premier repère ne remplace pas l’étude personnalisée de votre dossier.",
    diagQuestion: "Votre objectif principal",
    diagButton: "Voir mon parcours",
    resultPrefix: "Votre point de départ :",
    contactEyebrow: "Contact",
    contactTitle: "Parlons de votre projet",
    contactIntro: "Décrivez brièvement votre situation. Nous vous répondons en général sous 24 à 48 heures ouvrées.",
    contactName: "Nom",
    contactEmail: "E-mail",
    contactPhone: "Téléphone (optionnel)",
    contactSubject: "Motif de la demande",
    contactMessage: "Votre message",
    contactSubmit: "Envoyer le message",
    contactConsent: "J’autorise MadaPath à utiliser les informations transmises afin de traiter ma demande.",
    contactSuccess: "Votre message a bien été envoyé. Nous vous répondrons dans les meilleurs délais.",
    contactError: "Une erreur est survenue. Veuillez réessayer ou nous contacter directement par e-mail.",
    subjects: [
      "Travailler à Madagascar",
      "Regroupement familial",
      "Investir à Madagascar",
      "Autre demande",
    ],
    footerText: "L’accompagnement administratif humain pour avancer sereinement à Madagascar.",
    footerNav: "Navigation",
    footerContact: "Contact",
    footerLegal: "Informations",
    legal: "MadaPath fournit une assistance administrative et ne garantit jamais une décision relevant des autorités compétentes.",
    faqTitle: "Questions fréquentes",
    faq: [
      {
        q: "MadaPath garantit-il l'acceptation de mon dossier ?",
        a: "Non. MadaPath prépare et accompagne les démarches dans les limites autorisées. La décision finale appartient toujours aux autorités compétentes.",
      },
      {
        q: "Quand faut-il commencer les démarches ?",
        a: "Le plus tôt possible. Certaines procédures nécessitent des pièces précises et des délais variables. Un premier échange permet de définir le calendrier adapté.",
      },
      {
        q: "Pouvez-vous vérifier mes documents avant le dépôt ?",
        a: "Oui. L'analyse et la vérification des pièces font partie intégrante de notre accompagnement.",
      },
      {
        q: "Proposez-vous un accompagnement en français et en anglais ?",
        a: "Oui, nos échanges se font dans les deux langues selon votre préférence.",
      },
      {
        q: "Puis-je demander une première évaluation de ma situation ?",
        a: "Oui. Le pré-diagnostic gratuit sur cette page est un premier repère. Pour une analyse détaillée, contactez-nous directement.",
      },
    ],
    pricingEyebrow: "Honoraires",
    pricingTitle: "Nos tarifs, en toute transparence",
    pricingIntro: "Les honoraires ci-dessous correspondent à l'accompagnement professionnel de MadaPath. Les frais administratifs et dépenses externes ne sont pas inclus.",
    disclaimer: "MadaPath fournit une assistance administrative pour la préparation, la vérification, le dépôt autorisé et le suivi des demandes. MadaPath ne délivre aucun visa ou titre de séjour et ne peut garantir une décision favorable. La décision finale appartient exclusivement aux autorités compétentes.",
    adminFeesBoxTitle: "Frais administratifs en supplément",
    adminFeesBoxText: "Les droits consulaires, frais gouvernementaux et dépenses externes ne sont pas compris dans les honoraires MadaPath. Ils varient selon le profil, la nationalité, le type de demande et la durée du séjour. Une estimation personnalisée est communiquée après l'analyse initiale du dossier. Les dépenses sont effectuées sur justificatifs lorsque ceux-ci sont délivrés par l'organisme concerné.",
    adminFeesRanges: "À titre purement indicatif, certains droits liés au visa long séjour ont été publiés dans une fourchette d'environ 150 000 à 497 500 Ar. Selon la catégorie et la durée, certaines cartes de résident peuvent représenter environ 300 à 534 €. Le coût du visa transformable dépend notamment de la représentation diplomatique compétente et de la catégorie de la demande. Ces montants peuvent être modifiés par les autorités et doivent être vérifiés avant chaque dépôt.",
    adminFeesThirdParty: "Les traductions, légalisations, assurances, déplacements, documents délivrés à l'étranger et autres prestations de tiers font l'objet d'une estimation séparée.",
    adminFeesDisclaimer: "Les conversions en ariary et en dollars sont fournies à titre indicatif. Le montant définitif et le taux de conversion applicable sont précisés dans le devis personnalisé.",
    paymentTitle: "Modalités de paiement",
    paymentStartTitle: "Au démarrage du dossier",
    paymentStartText: "Le premier versement de 50 % déclenche l'analyse détaillée du dossier, la remise de la liste personnalisée des pièces, la vérification des documents, la préparation administrative et les premières démarches prévues dans le devis.",
    paymentSuccessTitle: "En cas de succès",
    paymentSuccessText: "En cas d'issue favorable, le solde de 50 % des honoraires MadaPath est payable lors de la remise ou de la mise à disposition des documents obtenus.",
    paymentRefusalTitle: "En cas de refus administratif",
    paymentRefusalText: "En cas de refus par l'autorité compétente, aucun solde d'honoraires supplémentaire ne sera demandé. Les 50 % d'honoraires déjà versés ainsi que les frais administratifs et dépenses externes déjà engagés ne sont toutefois pas remboursables.",
    processTimeline: [
      "Évaluation du dossier",
      "Devis personnalisé",
      "Paiement de 50 % + provision administrative",
      "Préparation et suivi",
      "Décision administrative",
      "Paiement du solde uniquement en cas de succès",
      "Remise des documents",
    ],
    viewDetails: "Voir les détails",
    requestAssessment: "Demander une évaluation",
    administrativeFeesExcluded: "hors frais administratifs",
    included: "Inclus",
    notIncluded: "Non inclus",
    popularService: "Demandé fréquemment",
    ogTitle: "MadaPath | Travailler, investir et s'installer à Madagascar",
    ogDescription: "MadaPath vous accompagne dans vos démarches pour travailler, investir ou rejoindre votre famille à Madagascar. Assistance administrative personnalisée.",
  },
  en: {
    lang: "en" as const,
    top: "Administrative support in Antananarivo · Français / English",
    nav: { services: "Services", method: "Our method", contact: "Contact", cta: "Assess my case" },
    eyebrow: "Your move, a path we take together",
    title: (
      <>
        Your move to Madagascar, made <em>clearer.</em>
      </>
    ),
    lead: "MadaPath handles your procedures for working, reuniting your family or investing in Madagascar — from preparing the file to submissions and follow-up with the relevant authorities.",
    primary: "Assess my project",
    secondary: "Explore our services",
    trust: [
      "Procedures handled for you",
      "Personal follow-up",
      "Attend only when required",
    ],
    cardTitle: "We move the process forward for you",
    cardText: "We prepare, submit and follow every procedure that can be handled under mandate. You step in only when personal attendance is compulsory.",
    steps: [
      "Understand your situation",
      "Prepare and submit the file",
      "Follow the process through completion",
    ],
    servicesEyebrow: "A path for every situation",
    servicesTitle: "One expertise, three paths",
    servicesIntro: "Every status comes with different conditions. We shape the support around your actual situation, not a generic package.",
    learn: "Explore this path →",
    methodEyebrow: "The MadaPath method",
    methodTitle: "Clear from the first call to the final document",
    methodIntro: "We turn complex procedures into understandable, manageable steps.",
    method: [
      [
        "Assessment",
        "We identify your goal, current status and potential risks.",
      ],
      [
        "Collection",
        "We request only the documents and information required for your situation.",
      ],
      [
        "Handling",
        "We prepare and carry out eligible procedures with EDBM, consular services, TLScontact or the relevant authorities.",
      ],
      [
        "Follow-up",
        "We track your file, keep you informed and attend with you when your personal presence is compulsory.",
      ],
    ],
    diagEyebrow: "Free pre-assessment",
    diagTitle: "What brings you to Madagascar?",
    diagText: "Select your situation to identify the path most relevant to your plans. This first guide does not replace a personalised case review.",
    diagQuestion: "Your main goal",
    diagButton: "See my path",
    resultPrefix: "Your starting point:",
    contactEyebrow: "Contact",
    contactTitle: "Let’s discuss your project",
    contactIntro: "Describe your situation briefly. We typically respond within 24 to 48 business hours.",
    contactName: "Name",
    contactEmail: "Email",
    contactPhone: "Phone (optional)",
    contactSubject: "Reason for enquiry",
    contactMessage: "Your message",
    contactSubmit: "Send message",
    contactConsent: "I authorise MadaPath to use the information provided in order to process my enquiry.",
    contactSuccess: "Your message has been sent. We will get back to you as soon as possible.",
    contactError: "An error occurred. Please try again or contact us directly by email.",
    subjects: [
      "Work in Madagascar",
      "Family Reunification",
      "Invest in Madagascar",
      "Other Enquiry",
    ],
    footerText: "Human administrative support for a smoother journey in Madagascar.",
    footerNav: "Navigation",
    footerContact: "Contact",
    footerLegal: "Information",
    legal: "MadaPath provides administrative assistance and never guarantees decisions made by the competent authorities.",
    faqTitle: "Frequently Asked Questions",
    faq: [
      {
        q: "Does MadaPath guarantee that my application will be approved?",
        a: "No. MadaPath prepares and supports procedures within the authorised limits. The final decision always rests with the competent authorities.",
      },
      {
        q: "When should I start the process?",
        a: "As early as possible. Some procedures require specific documents and variable processing times. An initial conversation helps establish a suitable timeline.",
      },
      {
        q: "Can you review my documents before submission?",
        a: "Yes. Document analysis and verification are an integral part of our support.",
      },
      {
        q: "Is assistance available in English and French?",
        a: "Yes. We communicate in both languages according to your preference.",
      },
      {
        q: "Can I request an initial assessment of my situation?",
        a: "Yes. The free pre-assessment on this page is a first indicator. For a detailed review, please contact us directly.",
      },
    ],
    pricingEyebrow: "Pricing",
    pricingTitle: "Our fees, fully transparent",
    pricingIntro: "The fees below cover MadaPath's professional assistance. Administrative fees and third-party expenses are not included.",
    disclaimer: "MadaPath provides administrative assistance with the preparation, review, authorized filing and follow-up of applications. MadaPath does not issue visas or residence permits and cannot guarantee approval. The final decision rests exclusively with the competent authorities.",
    adminFeesBoxTitle: "Administrative fees are charged separately",
    adminFeesBoxText: "Consular fees, government charges and third-party expenses are not included in MadaPath's professional fees. They vary according to the applicant's profile, nationality, application type and requested duration of stay. A personalized estimate will be provided after the initial assessment. Expenses are documented whenever the relevant authority or provider issues supporting evidence.",
    adminFeesRanges: "For general guidance only, some published long-stay visa charges have ranged from approximately MGA 150,000 to MGA 497,500. Depending on the category and duration, certain residence permits may cost approximately €300 to €534. Transformable visa fees also depend on the competent diplomatic mission and the application category. These amounts may be changed by the authorities and must be verified before each submission.",
    adminFeesThirdParty: "Translations, legalizations, insurance, travel, foreign-issued documents and other third-party services are estimated separately.",
    adminFeesDisclaimer: "Prices displayed in Malagasy ariary and US dollars are indicative conversions only. The final amount and applicable exchange rate will be specified in the personalized quotation.",
    paymentTitle: "Payment terms",
    paymentStartTitle: "When engaging MadaPath",
    paymentStartText: "The initial 50% payment triggers the detailed case assessment, delivery of the personalized document checklist, document verification, administrative preparation and the first steps outlined in the quotation.",
    paymentSuccessTitle: "If the application is successful",
    paymentSuccessText: "If the application is successful, the remaining 50% of MadaPath's professional fees becomes payable when the approved documents are delivered or made available.",
    paymentRefusalTitle: "If the application is refused",
    paymentRefusalText: "If the application is refused by the competent authority, no remaining professional fee will be charged. However, the initial 50% professional fee and any administrative fees or third-party expenses already incurred are non-refundable.",
    processTimeline: [
      "Application assessment",
      "Personalized quotation",
      "50% professional fee + administrative provision",
      "Preparation and follow-up",
      "Administrative decision",
      "Remaining fee payable only upon success",
      "Document delivery",
    ],
    viewDetails: "View details",
    requestAssessment: "Request an assessment",
    administrativeFeesExcluded: "administrative fees excluded",
    included: "Included",
    notIncluded: "Not included",
    popularService: "Frequently requested",
    ogTitle: "MadaPath | Work, Invest and Relocate to Madagascar",
    ogDescription: "MadaPath assists professionals, investors and families with administrative procedures for working, investing and relocating to Madagascar.",
  },
};

export const services: Record<ServiceSlug, { icon: string; fr: { name: string; short: string; title: string; intro: string; items: string[]; included: string[]; notIncluded: string[] }; en: { name: string; short: string; title: string; intro: string; items: string[]; included: string[]; notIncluded: string[] } }> = {
  travailleur: {
    icon: "↗",
    fr: {
      name: "Visa transformable",
      short: "Accompagnement pour la demande de visa transformable, de l'évaluation initiale au suivi administratif.",
      title: "Travailler à Madagascar en toute conformité",
      intro: "MadaPath accompagne les professionnels dans la préparation et le suivi des démarches nécessaires pour travailler légalement à Madagascar.",
      items: [
        "Évaluation initiale de l'éligibilité",
        "Liste personnalisée des documents",
        "Contrôle de la cohérence et de la complétude du dossier",
        "Organisation des pièces",
        "Assistance dans la préparation de la demande",
        "Coordination avec la représentation ou l'organisme compétent",
        "Suivi administratif jusqu'à l'obtention d'une réponse",
        "Préparation du client aux étapes nécessitant sa présence",
      ],
      included: [
        "Évaluation initiale de l'éligibilité",
        "Liste personnalisée des documents",
        "Contrôle de la cohérence et de la complétude du dossier",
        "Organisation des pièces",
        "Assistance dans la préparation de la demande",
        "Coordination avec la représentation ou l'organisme compétent",
        "Suivi administratif jusqu'à l'obtention d'une réponse",
        "Préparation du client aux étapes nécessitant sa présence",
      ],
      notIncluded: [
        "Droits consulaires et gouvernementaux",
        "Traductions et légalisations",
        "Casier judiciaire et documents officiels",
        "Assurance",
        "Transport et hébergement",
        "Visa long séjour",
        "Carte de résident",
        "Frais ou prestations de tiers",
        "Représentation aux étapes exigeant légalement la présence du demandeur",
      ],
    },
    en: {
      name: "Transformable Visa",
      short: "Assistance with the transformable visa application, from initial assessment to administrative follow-up.",
      title: "Work in Madagascar with a compliant path",
      intro: "MadaPath assists professionals with the preparation and follow-up of the administrative procedures required to work legally in Madagascar.",
      items: [
        "Initial eligibility assessment",
        "Personalized document checklist",
        "Consistency and completeness review",
        "Organization of supporting documents",
        "Assistance with application preparation",
        "Coordination with the competent diplomatic mission or authority",
        "Administrative follow-up until a response is issued",
        "Preparation for steps requiring the applicant's personal attendance",
      ],
      included: [
        "Initial eligibility assessment",
        "Personalized document checklist",
        "Consistency and completeness review",
        "Organization of supporting documents",
        "Assistance with application preparation",
        "Coordination with the competent diplomatic mission or authority",
        "Administrative follow-up until a response is issued",
        "Preparation for steps requiring the applicant's personal attendance",
      ],
      notIncluded: [
        "Consular and government fees",
        "Translations and legalizations",
        "Criminal record and official documents",
        "Insurance",
        "Travel and accommodation",
        "Long-stay visa",
        "Residence card",
        "Third-party fees or services",
        "Representation at stages legally requiring the applicant's presence",
      ],
    },
  },
  famille: {
    icon: "⌃",
    fr: {
      name: "Regroupement familial",
      short: "Accompagnement pour le regroupement familial, les pièces d'état civil et l'installation de vos proches à Madagascar.",
      title: "Réunir votre famille à Madagascar",
      intro: "Nous accompagnons les couples et les familles dans la préparation de leurs démarches de regroupement et d'installation à Madagascar.",
      items: [
        "Analyse de la situation familiale",
        "Liste personnalisée des documents nécessaires",
        "Vérification et organisation du dossier",
        "Accompagnement administratif complet",
        "Suivi des démarches jusqu'à leur conclusion",
      ],
      included: [
        "Analyse de la situation familiale",
        "Vérification des conditions applicables",
        "Liste personnalisée des pièces",
        "Contrôle des actes de mariage et de naissance",
        "Contrôle des documents d'hébergement et de prise en charge",
        "Organisation et préparation du dossier",
        "Assistance au dépôt lorsque cela est autorisé",
        "Suivi administratif",
        "Préparation du demandeur aux rendez-vous obligatoires",
      ],
      notIncluded: [
        "Droits consulaires et gouvernementaux",
        "Frais de visa long séjour",
        "Carte de résident",
        "Traductions, apostilles ou légalisations",
        "Délivrance ou renouvellement des actes d'état civil",
        "Tests, assurances ou certificats médicaux éventuellement demandés",
        "Transport et hébergement",
        "Frais propres à chaque membre supplémentaire, sauf mention contraire dans le devis",
        "Prestations de tiers",
      ],
    },
    en: {
      name: "Family Reunification",
      short: "Assistance with family reunification, civil-status documents and settling relatives in Madagascar.",
      title: "Bring your family together in Madagascar",
      intro: "We assist couples and families in preparing their family reunification and relocation procedures in Madagascar.",
      items: [
        "Family situation assessment",
        "Personalised list of required documents",
        "Document verification and organisation",
        "Complete administrative support",
        "Follow-up of procedures through to completion",
      ],
      included: [
        "Assessment of the family situation",
        "Review of applicable eligibility conditions",
        "Personalized document checklist",
        "Review of marriage and birth certificates",
        "Review of accommodation and financial-support documents",
        "Organization and preparation of the application",
        "Filing assistance where legally permitted",
        "Administrative follow-up",
        "Preparation for mandatory appointments",
      ],
      notIncluded: [
        "Consular and government fees",
        "Long-stay visa fees",
        "Residence card",
        "Translations, apostilles or legalizations",
        "Issuance or renewal of civil-status records",
        "Tests, insurance or medical certificates if required",
        "Travel and accommodation",
        "Fees for each additional member, unless stated otherwise in the quotation",
        "Third-party services",
      ],
    },
  },
  investisseur: {
    icon: "◇",
    fr: {
      name: "Visa investisseur",
      short: "Accompagnement pour le visa investisseur lorsque la société ou la structure d'investissement nécessaire existe déjà.",
      title: "Investir à Madagascar avec une feuille de route claire",
      intro: "MadaPath accompagne les entrepreneurs et investisseurs étrangers dans leurs démarches de visa lorsqu'ils disposent déjà d'une structure d'investissement à Madagascar.",
      items: [
        "Diagnostic du projet et du profil investisseur",
        "Liste personnalisée des documents",
        "Vérification des documents personnels",
        "Contrôle des statuts, du RCS, du NIF/CIF, de la carte statistique et des documents fiscaux disponibles",
        "Vérification des attestations bancaires nécessaires",
        "Organisation et préparation du dossier",
        "Coordination avec l'EDBM et les autorités compétentes",
        "Assistance au dépôt lorsque cela est autorisé",
        "Suivi administratif",
        "Préparation aux rendez-vous exigeant la présence du demandeur",
      ],
      included: [
        "Diagnostic du projet et du profil investisseur",
        "Liste personnalisée des documents",
        "Vérification des documents personnels",
        "Contrôle des statuts, du RCS, du NIF/CIF, de la carte statistique et des documents fiscaux disponibles",
        "Vérification des attestations bancaires nécessaires",
        "Organisation et préparation du dossier",
        "Coordination avec l'EDBM et les autorités compétentes",
        "Assistance au dépôt lorsque cela est autorisé",
        "Suivi administratif",
        "Préparation aux rendez-vous exigeant la présence du demandeur",
      ],
      notIncluded: [
        "Création, constitution ou enregistrement d'une entreprise",
        "Rédaction de statuts complexes",
        "Capital social ou investissement",
        "Overture et frais de compte bancaire",
        "Comptabilité et déclarations fiscales",
        "Droits consulaires et gouvernementaux",
        "Visa transformable s'il doit faire l'objet d'une procédure distincte",
        "Visa long séjour et carte de résident",
        "Traductions et légalisations",
        "Déplacements, hébergement et transport",
        "Licences ou autorisations sectorielles",
        "Services de tiers",
      ],
    },
    en: {
      name: "Investor Visa",
      short: "Assistance with the investor visa when the required company or investment structure already exists.",
      title: "Invest in Madagascar with a clear roadmap",
      intro: "MadaPath assists foreign entrepreneurs and investors with their visa applications when they already have an investment structure in Madagascar.",
      items: [
        "Assessment of the investment project and investor profile",
        "Personalized document checklist",
        "Review of personal documents",
        "Review of available articles of association, company registration, tax identification, statistical registration and tax records",
        "Review of the required bank certificates",
        "Organization and preparation of the application",
        "Coordination with EDBM and the competent authorities",
        "Filing assistance where legally permitted",
        "Administrative follow-up",
        "Preparation for appointments requiring the applicant's attendance",
      ],
      included: [
        "Assessment of the investment project and investor profile",
        "Personalized document checklist",
        "Review of personal documents",
        "Review of available articles of association, company registration, tax identification, statistical registration and tax records",
        "Review of the required bank certificates",
        "Organization and preparation of the application",
        "Coordination with EDBM and the competent authorities",
        "Filing assistance where legally permitted",
        "Administrative follow-up",
        "Preparation for appointments requiring the applicant's attendance",
      ],
      notIncluded: [
        "Company formation, incorporation or registration",
        "Drafting of complex articles of association",
        "Share capital or investment",
        "Bank account opening and fees",
        "Accounting and tax filings",
        "Consular and government fees",
        "Transformable visa if a separate procedure is required",
        "Long-stay visa and residence card",
        "Translations and legalizations",
        "Travel, accommodation and transport",
        "Sector-specific licences or permits",
        "Third-party services",
      ],
    },
  },
};

export const images: Record<ServiceSlug, { src: string; alt: { fr: string; en: string } }> = {
  travailleur: {
    src: "/images/work.webp",
    alt: {
      fr: "Professionnel en réunion dans un environnement de travail moderne à Madagascar",
      en: "Professional in a modern work setting in Madagascar",
    },
  },
  famille: {
    src: "/images/family.webp",
    alt: {
      fr: "Couple et famille dans un cadre chaleureux à Madagascar",
      en: "Couple and family in a warm setting in Madagascar",
    },
  },
  investisseur: {
    src: "/images/invest.webp",
    alt: {
      fr: "Entrepreneur en réunion professionnelle à Madagascar",
      en: "Entrepreneur in a professional meeting in Madagascar",
    },
  },
};
